### ISSUE TITLE
Error while building

### ISSUE THREAD

**Issue by carlosrodriguez85** [zhicwu/docker-biserver-ce#25]
Whenever I try to build the docker image I get this error:

The command '/bin/sh -c wget -P $BISERVER_HOME/tomcat/webapps/pentaho/WEB-INF/lib https://github.com/zhicwu/saiku/releases/download/3.8.8-SNAPSHOT/saiku-olap-util-3.8.8.jar 	&& wget -O btable.zip https://github.com/zhicwu/BTable/releases/download/7.0-RC1/BTable-7.0-RC1.zip 	&& wget -O saiku-chart-plus.zip http://sourceforge.net/projects/saikuchartplus/files/SaikuChartPlus3/saiku-chart-plus-vSaiku3-plugin-pentaho.zip/download 	&& wget --progress=dot:giga https://github.com/zhicwu/saiku/releases/download/3.8.8-SNAPSHOT/saiku-plugin-p6-3.8.8.zip http://ci.pentaho.com/job/webdetails-cte/29/artifact/dist/cte-7.0-SNAPSHOT.zip 		http://ctools.pentaho.com/files/d3ComponentLibrary/14.06.18/d3ComponentLibrary-14.06.18.zip 		https://github.com/rpbouman/pash/raw/master/bin/pash.zip 	&& for i in *.zip; do echo "Unpacking $i..." && unzip -q -d pentaho-solutions/system $i && rm -f $i; done 	&& rm -f *.zip' returned a non-zero code: 8

**Comment by zhicwu** [comment]
It was working until they deleted build #29 of CTE on Pentaho CI. Anyway I fixed this and updated docker file in all branches. Try pull the change and let me know if it works on your end.

**Comment by carlosrodriguez85** [comment]
It now hangs for a while after I run "docker-compose up -d", on this step:

```
--2017-02-02 03:33:46--  https://github.com/OSBI/saiku/raw/release-3.8/saiku-bi-platform-plugin-p5/src/main/plugin/components/saikuWidget/SaikuWidgetComponent.js
Resolving github.com (github.com)... 192.30.253.113, 192.30.253.112
Connecting to github.com (github.com)|192.30.253.113|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/OSBI/saiku/release-3.8/saiku-bi-platform-plugin-p5/src/main/plugin/components/saikuWidget/SaikuWidgetComponent.js [following]
--2017-02-02 03:33:47--  https://raw.githubusercontent.com/OSBI/saiku/release-3.8/saiku-bi-platform-plugin-p5/src/main/plugin/components/saikuWidget/SaikuWidgetComponent.js
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.132.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.132.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1122 (1.1K) [text/plain]
Saving to: ‘pentaho-solutions/system/saiku/components/saikuWidget/SaikuWidgetComponent.js’

     0K .                                                     100% 55.8M=0s

2017-02-02 03:33:48 (55.8 MB/s) - ‘pentaho-solutions/system/saiku/components/saikuWidget/SaikuWidgetComponent.js’ saved [1122/1122]
```

Maybe there should a message informing the user that something is running behind the scenes?

Thanks a lot for your nice work!!

**Comment by zhicwu** [comment]
Thanks for taking your time try this. Building the docker image will take some time, so maybe you can just remove the line with "build: ." in docker-compose.yml file to skip that? I'll remove the extra line and update instructions tomorrow.

**Comment by carlosrodriguez85** [comment]
It also lasts a lot of time until it actually runs the pentaho server. All the process hangs after "Fixing permissions" for a long time.

**Comment by carlosrodriguez85** [comment]
Sorry again: After a while, I receive this message:

*** ./docker-entrypoint.sh exited with status 137.
*** Shutting down runit daemon (PID 7)...
*** Killing all processes...

And the docker container shuts down.

Maybe a newer version of some file is producing the error?

**Comment by zhicwu** [comment]
Sorry to hear about this. Are you using docker-compose? Can you try the first two approaches in readme to see if it works? You'd better issue the following commands firstly to ensure you removed the old container and downloaded latest image.

> docker stop bi; docker rm bi; docker pull zhicwu/biserver-ce:7.0

I saw your previous message and will refine shell script so that fixing permission won't take too long.

**Comment by carlosrodriguez85** [comment]
Now I have this issue. I want to clear up that I'm using Docker on top of Mac, could that be an issue?

11-Feb-2017 17:04:39.952 WARNING [main] org.apache.catalina.core.AprLifecycleListener.init The APR based Apache Tomcat Native library failed to load. The error reported was [/biserver-ce/tomcat/lib/libtcnative-1.so.0.2.8: libapr-1.so.0: cannot open shared object file: No such file or directory]
 java.lang.UnsatisfiedLinkError: /biserver-ce/tomcat/lib/libtcnative-1.so.0.2.8: libapr-1.so.0: cannot open shared object file: No such file or directory
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1857)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.apache.tomcat.jni.Library.<init>(Library.java:42)
	at org.apache.tomcat.jni.Library.initialize(Library.java:178)
	at org.apache.catalina.core.AprLifecycleListener.init(AprLifecycleListener.java:197)
	at org.apache.catalina.core.AprLifecycleListener.isAprAvailable(AprLifecycleListener.java:106)
	at org.apache.catalina.connector.Connector.setProtocol(Connector.java:564)
	at org.apache.catalina.connector.Connector.<init>(Connector.java:66)
	at org.apache.catalina.startup.ConnectorCreateRule.begin(ConnectorCreateRule.java:62)
	at org.apache.tomcat.util.digester.Digester.startElement(Digester.java:1193)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:509)
	at com.sun.org.apache.xerces.internal.parsers.AbstractXMLDocumentParser.emptyElement(AbstractXMLDocumentParser.java:182)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanStartElement(XMLDocumentFragmentScannerImpl.java:1339)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2784)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:841)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:770)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
	at org.apache.tomcat.util.digester.Digester.parse(Digester.java:1466)
	at org.apache.catalina.startup.Catalina.load(Catalina.java:552)
	at org.apache.catalina.startup.Catalina.load(Catalina.java:603)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.catalina.startup.Bootstrap.load(Bootstrap.java:310)
	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:484)

**Comment by zhicwu** [comment]
Thanks for reporting this and sorry for the late reply. I'll look into this tonight and update. Since it's a warning I guess the server itself is functional, right? I use mac too so it's not a problem.
